account/urls.py
from django.urls import path
from .views import register
from django.contrib.auth.views import (LoginView,LogoutView,
                                        PasswordChangeView,PasswordChangeDoneView,
                                        PasswordResetCompleteView,PasswordResetConfirmView,
                                        PasswordResetDoneView,PasswordResetView)

urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('password_change/',PasswordChangeView.as_view(),name="password_change"),
    path('password_change_done/',PasswordChangeDoneView.as_view(),name="password_change_done"),
    #reset password
    path('password_reset/',PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    #register
    path('register/',register,name="register")

]

article/urls.py
from django.urls import path,re_path
from .views import (ArticleCreateView,ArticleDetailView,
         ArticleUpdateView,ArticleListView,
         ArticleCounterView,DeleteArticleView,
         HomeView, CategoryList,SearchView,MyArticle)
app_name="article"

urlpatterns = [
    path('',HomeView.as_view(),name='index'),
    path('list/',ArticleListView.as_view(),name="list"),
    path('redirect/<pk>/',ArticleCounterView.as_view(),name='redirect'),
    path('<int:pk>/',ArticleDetailView.as_view(), name='detail'),
    path('create/',ArticleCreateView.as_view(), name='create'),
    path('<pk>/update', ArticleUpdateView.as_view(),name="update"),
    path('<pk>/delete/',DeleteArticleView.as_view(),name='delete'),
    path('categories/',CategoryList.as_view(),name='category'),
    path('search/',SearchView.as_view(),name='search'),
    path('mine/',MyArticle.as_view(),name="mine"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('i18n/',include('django.conf.urls.i18n'))
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns+= i18n_patterns(
    path('accounts/',include('account.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',include('article.urls')),

)

account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    job = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    picture = models.ImageField(upload_to='profiles/')

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(label="password",widget=forms.PasswordInput)
    password2 = forms.CharField(label="repeate password",widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username','email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('password dont mach')
        return cd['password2']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('job','picture','description',)

account/views.py
from django.shortcuts import render
from .forms import RegisterUserForm, ProfileForm

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        profile_form = ProfileForm(request.POST,request.FILES)
        if form.is_valid() and profile_form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password2'])
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return render(request,'account/register_done.html',{'user':user})
    else:
        form = RegisterUserForm()
        profile_form = ProfileForm()
    return render(request,'account/register.html',{'form':form,'profile_form':profile_form})

account/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>{% block title %}{% trans "Home" %}{% endblock title %}</title>
	<meta name="description" content="Katen - Minimal Blog & Magazine HTML Theme">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="images/favicon.png">

	<!-- STYLES -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'css/all.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'css/slick.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
</head>
<body>
    <!-- preloader -->
	<div id="preloader">
		<div class="book">
			<div class="inner">
				<div class="left"></div>
				<div class="middle"></div>
				<div class="right"></div>
			</div>
			<ul>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
			</ul>
		</div>
	</div>
    <div class="site-wrapper">
    <div class="main-overlay"></div>

    {% block navbar %}
		{% include 'navbar.html' %}
    {% endblock navbar %}
    {% block content %}

    {% endblock content %}
    <footer>
        <div class="container-xl">
            <div class="footer-inner">
                <div class="row d-flex align-items-center gy-4">
                    <!-- copyright text -->
                    <div class="col-md-4">
                        <span class="copyright">© 2021 Katen. Template by ThemeGer.</span>
                    </div>

                    <!-- social icons -->
                    <div class="col-md-4 text-center">
                        <ul class="social-icons list-unstyled list-inline mb-0">
                            <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
                        </ul>
                    </div>

                    <!-- go to top button -->
                    <div class="col-md-4">
                        <a href="#" id="return-to-top" class="float-md-end"><i class="icon-arrow-up"></i>Back to
                            Top</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    </div>
    {% include 'side_menu.html' %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky-sidebar.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

account/templates/navbar.html
{% load static %}
{% load i18n %}
<header class="header-default">
    <nav class="navbar navbar-expand-lg">
        <div class="container-xl">
            <!-- site logo -->
            <a class="navbar-brand" href="index.html"><img src="{% static 'images/logo.svg' %}" alt="logo" /></a>

            <div class="collapse navbar-collapse">
                <!-- menus -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'article:index' %}">{% trans "Home" %}</a>
                    </li>
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle" href="{% url 'article:index' %}">{% trans "Categories" %}</a>
                        <ul class="dropdown-menu">
                            {% for category in categories %}
                            <li><a class="dropdown-item" href="{% url 'article:category' %}?category={{category.name}}">{{category.name}}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">{% trans "Contact" %}</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">{% trans "Logout" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'article:mine' %}">{% trans "My Articles" %}</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">{% trans "Login" %}</a>
                    </li>
                    {% endif %}
                    <li><form action="{% url 'set_language' %}" method="post">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}" >
                        {% if LANGUAGE_CODE == 'en' %}
                        <button class="btn btn-primary px-4" type="submit" value="ar" name="language"><span class="text-black">ar</span></btton>
                        {% elif LANGUAGE_CODE == 'ar' %}
                        <button class="btn btn-primary px-4" type="submit" value="en" name="language"><span class="text-black">en</span></button>
                        {% endif %}
                      </form></li>
                </ul>
            </div>

            <!-- header right section -->
            <div class="header-right">
                <!-- social icons -->
                <ul class="social-icons list-unstyled list-inline mb-0">
                    <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
                </ul>
                <!-- header buttons -->
                <div class="header-buttons">
                    <button class="search icon-button">
                        <i class="icon-magnifier"></i>
                    </button>
                    <button class="burger-menu icon-button">
                        <span class="burger-icon"></span>
                    </button>
                </div>
            </div>
        </div>
    </nav>
</header>

account/templates/side_menu.html
{% load static %}
{% load i18n %}
<div class="search-popup">
    <!-- close button -->
    <button type="button" class="btn-close" aria-label="Close"></button>
    <!-- content -->
    <div class="search-content">
        <div class="text-center">
            <h3 class="mb-4 mt-0">{% trans "Press ESC to close" %}</h3>
        </div>
        <!-- form -->
        <form action="{% url 'article:search' %}" class="d-flex search-form">
            <input name="search" class="form-control me-2" type="search" placeholder="{% trans "Search and press enter ..." %}"
                aria-label="Search">
            <button class="btn btn-default btn-lg" type="submit"><i class="icon-magnifier"></i></button>
        </form>
        
    </div>
</div>

<!-- canvas menu -->
<div class="canvas-menu d-flex align-items-end flex-column">
    <!-- close button -->
    <button type="button" class="btn-close" aria-label="Close"></button>

    <!-- logo -->
    <div class="logo">
        <img src="{% static 'images/logo.svg' %}" alt="Katen" />
    </div>

    <!-- menu -->
    <nav>
        <ul class="vertical-menu">
            <li class="active"><a href="{% url 'article:index' %}">{% trans "Home" %}</a></li>
            <li>
                <a href="index.html">{% trans "Category" %}</a>
                <ul class="submenu">
                    {% for category in categories %}
                    <li><a href="{% url 'article:category' %}?category={{category.name}}">{{category.name}}</a></li>

                    {% endfor %}                    
                </ul>
            </li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
            {% else %}
                <li><a href="{% url 'register' %}">{% trans "Register" %}</a></li>
                <li><a href="{% url 'loging' %}">{% trans "Login" %}</a></li>
            {% endif %}
            <li><a href="contact.html">{% trans "Contact" %}</a></li>
        </ul>
    </nav>

    <!-- social icons -->
    <ul class="social-icons list-unstyled list-inline mb-0 mt-auto w-100">
        <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
        <li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
    </ul>
</div>